# For local development
# Make sure when creating the environment you have installed conda
# conda env create -f *Name of This File (ex. requirements.yaml)*
# Select "install ikernel" when popup appears when first activating running a cell in an .ipynb file with the env
# Use: "conda activate *Name of Env (ex. my_env)*" when running scripts in the terminal to activate the environment

name: CC_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _python_abi3_support=1.0
  - aws-c-auth=0.9.1
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.4
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.6
  - aws-c-http=0.10.4
  - aws-c-io=0.22.0
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.8.6
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.34.4
  - aws-sdk-cpp=1.11.606
  - blas=1.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.8.3
  - certifi=2025.8.3
  - cffi=2.0.0
  - charset-normalizer=3.4.3
  - colorama=0.4.6
  - contourpy=1.3.3
  - cpython=3.12.11
  - cuda-cccl=13.0.85
  - cuda-cccl_win-64=13.0.85
  - cuda-cudart=12.4.127
  - cuda-cudart-dev=12.4.127
  - cuda-cupti=12.4.127
  - cuda-libraries=12.4.1
  - cuda-libraries-dev=12.4.1
  - cuda-nvrtc=12.4.127
  - cuda-nvrtc-dev=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-opencl=13.0.85
  - cuda-opencl-dev=13.0.85
  - cuda-profiler-api=13.0.85
  - cuda-runtime=12.4.1
  - cuda-version=13.0
  - cycler=0.12.1
  - filelock=3.19.1
  - fonttools=4.60.0
  - freetype=2.14.1
  - fsspec=2025.9.0
  - h2=4.3.0
  - hf-xet=1.1.10
  - hpack=4.1.0
  - huggingface_hub=0.35.1
  - hyperframe=6.1.0
  - idna=3.10
  - imbalanced-learn=0.14.0
  - intel-openmp=2025.2.0
  - jinja2=3.1.6
  - joblib=1.5.2
  - khronos-opencl-icd-loader=2024.10.24
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20250512.1
  - libarrow=21.0.0
  - libarrow-acero=21.0.0
  - libarrow-compute=21.0.0
  - libarrow-dataset=21.0.0
  - libarrow-substrait=21.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcublas=12.4.5.8
  - libcublas-dev=12.4.5.8
  - libcufft=11.2.1.3
  - libcufft-dev=11.2.1.3
  - libcurand=10.4.0.35
  - libcurand-dev=10.4.0.35
  - libcurl=8.14.1
  - libcusolver=11.6.1.9
  - libcusolver-dev=11.6.1.9
  - libcusparse=12.3.1.170
  - libcusparse-dev=12.3.1.170
  - libdeflate=1.24
  - libevent=2.1.12
  - libexpat=2.7.1
  - libffi=3.4.6
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgoogle-cloud=2.39.0
  - libgoogle-cloud-storage=2.39.0
  - libgrpc=1.73.1
  - libhwloc=2.12.1
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libnpp=12.2.5.30
  - libnpp-dev=12.2.5.30
  - libnvfatbin=13.0.85
  - libnvfatbin-dev=13.0.85
  - libnvjitlink=12.4.127
  - libnvjitlink-dev=12.4.127
  - libnvjpeg=12.3.1.117
  - libnvjpeg-dev=12.3.1.117
  - libparquet=21.0.0
  - libpng=1.6.50
  - libprotobuf=6.31.1
  - libre2-11=2025.08.12
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libthrift=0.22.0
  - libtiff=4.7.1
  - libutf8proc=2.11.0
  - libuv=1.51.0
  - libwebp-base=1.6.0
  - libxcb=1.16
  - libxml2=2.13.8
  - libzlib=1.3.1
  - lz4-c=1.10.0
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=3.0.2
  - matplotlib-base=3.10.6
  - mkl=2023.1.0
  - mpmath=1.3.0
  - msys2-conda-epoch=20160418
  - munkres=1.1.4
  - networkx=3.5
  - numpy=2.3.3
  - opencl-headers=2025.06.13
  - openjpeg=2.5.4
  - openssl=3.5.3
  - orc=2.2.0
  - packaging=25.0
  - pandas=2.3.2
  - patsy=1.0.1
  - pillow=10.4.0
  - pip=25.2
  - pthread-stubs=0.4
  - pyarrow=21.0.0
  - pyarrow-core=21.0.0
  - pycparser=2.22
  - pyparsing=3.2.5
  - pysocks=1.7.1
  - python=3.12.11
  - python-dateutil=2.9.0.post0
  - python-gil=3.12.11
  - python-tzdata=2025.2
  - python_abi=3.12
  - pytorch=2.5.1
  - pytorch-cuda=12.4
  - pytorch-mutex=1.0
  - pytz=2025.2
  - pyyaml=6.0.3
  - qhull=2020.2
  - re2=2025.08.12
  - requests=2.32.5
  - scikit-learn=1.7.2
  - scipy=1.16.2
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=80.9.0
  - six=1.17.0
  - snappy=1.2.2
  - statsmodels=0.14.5
  - sympy=1.14.0
  - tbb=2021.13.0
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tqdm=4.67.1
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - ucrt=10.0.26100.0
  - unicodedata2=16.0.0
  - urllib3=2.5.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vcomp14=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - yaml=0.2.5
  - zstandard=0.25.0
  - zstd=1.5.7